import { type NextRequest, NextResponse } from "next/server"
import type { Customer } from "../../types/customer"

// Processed Meta LLama customer data
const customers: Customer[] = [
  {
    id: "1",
    name: "Sarah Chen",
    company: "Sarah Technology Corp",
    industry: "technology",
    region: "north-america",
    revenue: 125000,
    dealSize: 15625,
    contractLength: 24,
    status: "active",
    notes: "Acquired via Employee Referral. Strong ongoing relationship.",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "2",
    name: "Michael Rodriguez",
    company: "Michael Healthcare Corp",
    industry: "healthcare",
    region: "north-america",
    revenue: 89000,
    dealSize: 11125,
    contractLength: 18,
    status: "active",
    notes: "Acquired via Google Ads Campaign. Strong ongoing relationship.",
    createdAt: new Date("2023-02-03"),
  },
  {
    id: "3",
    name: "Jennifer Park",
    company: "Jennifer Financial Corp",
    industry: "finance",
    region: "north-america",
    revenue: 156000,
    dealSize: 19500,
    contractLength: 30,
    status: "active",
    notes: "Acquired via Company Website. Strong ongoing relationship.",
    createdAt: new Date("2023-02-18"),
  },
  {
    id: "4",
    name: "David Thompson",
    company: "David E-commerce Corp",
    industry: "retail",
    region: "north-america",
    revenue: 78000,
    dealSize: 9750,
    contractLength: 15,
    status: "inactive",
    notes: "Acquired via LinkedIn Advertisement. Left due to: Budget Constraints",
    createdAt: new Date("2023-03-05"),
  },
  {
    id: "5",
    name: "Lisa Wang",
    company: "Lisa Education Corp",
    industry: "education",
    region: "north-america",
    revenue: 92000,
    dealSize: 11500,
    contractLength: 22,
    status: "active",
    notes: "Acquired via Industry Conference. Strong ongoing relationship.",
    createdAt: new Date("2023-03-22"),
  },
  {
    id: "6",
    name: "Robert Martinez",
    company: "Robert Manufacturing Corp",
    industry: "manufacturing",
    region: "north-america",
    revenue: 134000,
    dealSize: 16750,
    contractLength: 28,
    status: "active",
    notes: "Acquired via Partner Referral. Strong ongoing relationship.",
    createdAt: new Date("2023-04-10"),
  },
  {
    id: "7",
    name: "Emily Davis",
    company: "Emily Media Corp",
    industry: "media",
    region: "north-america",
    revenue: 67000,
    dealSize: 8375,
    contractLength: 16,
    status: "inactive",
    notes: "Acquired via Social Media Ad. Left due to: Switched to Competitor",
    createdAt: new Date("2023-04-28"),
  },
  {
    id: "8",
    name: "James Wilson",
    company: "James Automotive Corp",
    industry: "automotive",
    region: "north-america",
    revenue: 145000,
    dealSize: 18125,
    contractLength: 32,
    status: "active",
    notes: "Acquired via Trade Show. Strong ongoing relationship.",
    createdAt: new Date("2023-05-14"),
  },
  {
    id: "9",
    name: "Maria Garcia",
    company: "Maria Real Corp",
    industry: "real-estate",
    region: "north-america",
    revenue: 83000,
    dealSize: 10375,
    contractLength: 19,
    status: "active",
    notes: "Acquired via Cold Outreach. Strong ongoing relationship.",
    createdAt: new Date("2023-05-30"),
  },
  {
    id: "10",
    name: "Christopher Lee",
    company: "Christopher Retail Corp",
    industry: "retail",
    region: "north-america",
    revenue: 98000,
    dealSize: 12250,
    contractLength: 25,
    status: "active",
    notes: "Acquired via Webinar Attendance. Strong ongoing relationship.",
    createdAt: new Date("2023-06-16"),
  },
  {
    id: "11",
    name: "Amanda Johnson",
    company: "Amanda Legal Corp",
    industry: "legal",
    region: "north-america",
    revenue: 112000,
    dealSize: 14000,
    contractLength: 27,
    status: "inactive",
    notes: "Acquired via Employee Referral. Left due to: Company Restructuring",
    createdAt: new Date("2023-07-02"),
  },
  {
    id: "12",
    name: "Ryan Brown",
    company: "Ryan Energy Corp",
    industry: "energy",
    region: "north-america",
    revenue: 167000,
    dealSize: 20875,
    contractLength: 35,
    status: "active",
    notes: "Acquired via Industry Publication. Strong ongoing relationship.",
    createdAt: new Date("2023-07-19"),
  },
  {
    id: "13",
    name: "Nicole Taylor",
    company: "Nicole Logistics Corp",
    industry: "logistics",
    region: "europe",
    revenue: 76000,
    dealSize: 9500,
    contractLength: 18,
    status: "active",
    notes: "Acquired via Google Ads Campaign. Strong ongoing relationship.",
    createdAt: new Date("2023-08-05"),
  },
  {
    id: "14",
    name: "Kevin Anderson",
    company: "Kevin Insurance Corp",
    industry: "insurance",
    region: "north-america",
    revenue: 129000,
    dealSize: 16125,
    contractLength: 29,
    status: "active",
    notes: "Acquired via Company Website. Strong ongoing relationship.",
    createdAt: new Date("2023-08-22"),
  },
  {
    id: "15",
    name: "Rachel Moore",
    company: "Rachel Pharmaceutical Corp",
    industry: "healthcare",
    region: "europe",
    revenue: 188000,
    dealSize: 23500,
    contractLength: 36,
    status: "active",
    notes: "Acquired via Research Partnership. Strong ongoing relationship.",
    createdAt: new Date("2023-09-08"),
  },
  {
    id: "16",
    name: "Brandon White",
    company: "Brandon Food Corp",
    industry: "food",
    region: "europe",
    revenue: 71000,
    dealSize: 8875,
    contractLength: 17,
    status: "inactive",
    notes: "Acquired via LinkedIn Advertisement. Left due to: Technical Issues",
    createdAt: new Date("2023-09-25"),
  },
  {
    id: "17",
    name: "Stephanie Harris",
    company: "Stephanie Telecommunications Corp",
    industry: "telecommunications",
    region: "asia-pacific",
    revenue: 143000,
    dealSize: 17875,
    contractLength: 31,
    status: "active",
    notes: "Acquired via Industry Conference. Strong ongoing relationship.",
    createdAt: new Date("2023-10-12"),
  },
  {
    id: "18",
    name: "Justin Clark",
    company: "Justin Gaming Corp",
    industry: "gaming",
    region: "asia-pacific",
    revenue: 95000,
    dealSize: 11875,
    contractLength: 23,
    status: "active",
    notes: "Acquired via YouTube Sponsorship. Strong ongoing relationship.",
    createdAt: new Date("2023-10-29"),
  },
  {
    id: "19",
    name: "Melissa Lewis",
    company: "Melissa Agriculture Corp",
    industry: "agriculture",
    region: "north-america",
    revenue: 86000,
    dealSize: 10750,
    contractLength: 20,
    status: "active",
    notes: "Acquired via Partner Referral. Strong ongoing relationship.",
    createdAt: new Date("2023-11-15"),
  },
  {
    id: "20",
    name: "Tyler Robinson",
    company: "Tyler Construction Corp",
    industry: "construction",
    region: "north-america",
    revenue: 108000,
    dealSize: 13500,
    contractLength: 26,
    status: "inactive",
    notes: "Acquired via Trade Show. Left due to: Budget Constraints",
    createdAt: new Date("2023-12-01"),
  },
]

export async function GET() {
  return NextResponse.json(customers)
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    const newCustomer: Customer = {
      id: Date.now().toString(),
      ...body,
      createdAt: new Date(),
    }

    customers.push(newCustomer)

    return NextResponse.json(newCustomer, { status: 201 })
  } catch (error) {
    return NextResponse.json({ error: "Failed to create customer" }, { status: 500 })
  }
}
